version: '3'
services:
  # Application Dockerfile is in the same folder.
  app:
    build: .

  # db is is db folder
  db:
    build: db/.
    restart: always
    ports:
      - "33060:3306"

  # dummy container so that one exits and actions doesn't keep running
  # Dockerlile entrypoint is 1-min sleep
  dummy:
    build: dummy/.