package com.napier.devops.entity;

/**
 * A base class for the various types of reports generated by the system (Country, City, Capital City, Population, Language)
 */
abstract class Report {
    private String name;
    private long population;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getPopulation() {
        return population;
    }

    public void setPopulation(long population) {
        this.population = population;
    }
}
