name: DevOps Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Start Using Docker Compose
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Package and run Docker Compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit
